/*
 * CiviBox - Minimal userspace toolkit for Linux
 *
 * Copyright (C) 2026 Pietro Carlini
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

#include <ncurses.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../etc/commands.c"

#define MAX_COMMANDS 256
#define CONFIG_FILE ".config"

enum
{
    MENU_MAIN,
    MENU_COMPILE,
    MENU_COMMANDS
};

struct config
{
    int compile_static;
    int commands[MAX_COMMANDS];
};

static struct config cfg;

static int command_count(void)
{
    int count = 0;

    while (command_list[count] != NULL &&
           count < MAX_COMMANDS)
    {
        count++;
    }

    return count;
}

static void config_name(char *buffer,
                        size_t size,
                        const char *command)
{
    size_t len = 0;

    if (size == 0)
        return;

    const char *prefix = "CONFIG_";

    while (*prefix && len + 1 < size)
        buffer[len++] = *prefix++;

    for (size_t i = 0;
         command[i] != '\0' && len + 1 < size;
         i++)
    {
        char c = command[i];

        if (c >= 'a' && c <= 'z')
            c -= 'a' - 'A';

        len++;
        buffer[len - 1] = c;
    }

    buffer[len] = '\0';
}

static void load_config(void)
{
    FILE *file = fopen(CONFIG_FILE, "r");

    if (!file)
    {
        cfg.compile_static = 1;

        for (int i = 0; i < command_count(); i++)
            cfg.commands[i] = 1;

        return;
    }

    char line[256];

    while (fgets(line, sizeof(line), file))
    {
        if (strncmp(line,
                    "CONFIG_COMPILE_STATIC=y",
                    23) == 0)
        {
            cfg.compile_static = 1;
            continue;
        }

        for (int i = 0; i < command_count(); i++)
        {
            char name[128];

            config_name(name,
                        sizeof(name),
                        command_list[i]);

            char enabled[160];

            snprintf(enabled,
                     sizeof(enabled),
                     "%s=y",
                     name);

            if (strncmp(line,
                        enabled,
                        strlen(enabled)) == 0)
            {
                cfg.commands[i] = 1;
                break;
            }

            char disabled[180];

            snprintf(disabled,
                     sizeof(disabled),
                     "# %s is not set",
                     name);

            if (strncmp(line,
                        disabled,
                        strlen(disabled)) == 0)
            {
                cfg.commands[i] = 0;
                break;
            }
        }
    }

    fclose(file);
}

static void save_config(void)
{
    FILE *file = fopen(CONFIG_FILE, "w");

    if (!file)
        return;

    fprintf(file,
            "#\n"
            "# CiviBox configuration\n"
            "# Automatically generated by menuconfig\n"
            "#\n\n");

    fprintf(file,
            "CONFIG_COMPILE_STATIC=%c\n\n",
            cfg.compile_static ? 'y' : 'n');

    for (int i = 0; i < command_count(); i++)
    {
        char name[128];

        config_name(name,
                    sizeof(name),
                    command_list[i]);

        if (cfg.commands[i])
        {
            fprintf(file,
                    "%s=y\n",
                    name);
        }
        else
        {
            fprintf(file,
                    "# %s is not set\n",
                    name);
        }
    }

    fclose(file);
}

static void draw_header(const char *title)
{
    attron(COLOR_PAIR(1) | A_BOLD);

    mvhline(0,
            0,
            ' ',
            COLS);

    int x = (COLS - (int)strlen(title)) / 2;

    if (x < 0)
        x = 0;

    mvprintw(0,
             x,
             "%s",
             title);

    attroff(COLOR_PAIR(1) | A_BOLD);
}

static void draw_footer(void)
{
    int row = LINES - 2;

    attron(COLOR_PAIR(1));

    mvhline(row,
            0,
            ' ',
            COLS);

    mvhline(row + 1,
            0,
            ' ',
            COLS);

    mvprintw(row,
             2,
             "<Enter> Select   <Space> Toggle   <Esc> Back");

    mvprintw(row + 1,
             2,
             "<S> Save         <Q> Quit");

    attroff(COLOR_PAIR(1));
}

static void draw_item(int row,
                      int selected,
                      const char *text)
{
    if (selected)
        attron(COLOR_PAIR(2) | A_BOLD);
    else
        attron(COLOR_PAIR(1));

    mvhline(row,
            0,
            ' ',
            COLS);

    mvprintw(row,
             3,
             "%s",
             text);

    if (selected)
        attroff(COLOR_PAIR(2) | A_BOLD);
    else
        attroff(COLOR_PAIR(1));
}

static void compile_menu(void)
{
    int selected = 0;
    int running = 1;

    while (running)
    {
        erase();

        draw_header("Compile settings");

        char text[128];

        snprintf(text,
                 sizeof(text),
                 "[%c] COMPILE_STATIC",
                 cfg.compile_static ? '*' : ' ');

        draw_item(3,
                  selected == 0,
                  text);

        draw_footer();

        refresh();

        int key = getch();

        switch (key)
        {
            case KEY_UP:
                selected = 0;
                break;

            case KEY_DOWN:
                selected = 0;
                break;

            case ' ':
                cfg.compile_static =
                    !cfg.compile_static;
                break;

            case 's':
            case 'S':
                save_config();
                break;

            case 27:
                running = 0;
                break;

            case 'q':
            case 'Q':
                running = 0;
                break;
        }
    }
}

static void commands_menu(void)
{
    int selected = 0;
    int running = 1;

    int count = command_count();

    while (running)
    {
        erase();

        draw_header("Commands");

        int visible = LINES - 7;

        if (visible < 1)
            visible = 1;

        int start = 0;

        if (selected >= visible)
            start = selected - visible + 1;

        for (int i = 0;
             i < visible &&
             start + i < count;
             i++)
        {
            int index = start + i;

            char text[128];

            snprintf(text,
                     sizeof(text),
                     "[%c] %s",
                     cfg.commands[index] ? '*' : ' ',
                     command_list[index]);

            draw_item(3 + i,
                      selected == index,
                      text);
        }

        draw_footer();

        refresh();

        int key = getch();

        switch (key)
        {
            case KEY_UP:
                if (selected > 0)
                    selected--;

                break;

            case KEY_DOWN:
                if (selected < count - 1)
                    selected++;

                break;

            case KEY_NPAGE:
                selected += visible;

                if (selected >= count)
                    selected = count - 1;

                break;

            case KEY_PPAGE:
                selected -= visible;

                if (selected < 0)
                    selected = 0;

                break;

            case KEY_HOME:
                selected = 0;
                break;

            case KEY_END:
                selected = count - 1;
                break;

            case ' ':
                if (count > 0)
                {
                    cfg.commands[selected] =
                        !cfg.commands[selected];
                }

                break;

            case 's':
            case 'S':
                save_config();
                break;

            case 27:
                running = 0;
                break;

            case 'q':
            case 'Q':
                running = 0;
                break;
        }
    }
}

static void main_menu(void)
{
    int selected = 0;

    const char *items[] =
    {
        "Compile settings  --->",
        "Commands          --->"
    };

    const int count = 2;

    int running = 1;

    while (running)
    {
        erase();

        draw_header("CiviBox Configuration");

        for (int i = 0; i < count; i++)
        {
            draw_item(3 + i,
                      selected == i,
                      items[i]);
        }

        draw_footer();

        refresh();

        int key = getch();

        switch (key)
        {
            case KEY_UP:
                if (selected > 0)
                    selected--;

                break;

            case KEY_DOWN:
                if (selected < count - 1)
                    selected++;

                break;

            case '\n':
            case KEY_ENTER:

                if (selected == 0)
                    compile_menu();

                else if (selected == 1)
                    commands_menu();

                break;

            case 's':
            case 'S':
                save_config();
                break;

            case 27:
            case 'q':
            case 'Q':
                running = 0;
                break;
        }
    }
}

int main(void)
{
    load_config();

    initscr();

    if (has_colors())
    {
        start_color();
        init_pair(1,
                  COLOR_WHITE,
                  COLOR_BLUE);

        init_pair(2,
                  COLOR_BLUE,
                  COLOR_WHITE);

        bkgd(COLOR_PAIR(1));
    }

    cbreak();
    noecho();

    keypad(stdscr, TRUE);

    curs_set(0);

    main_menu();

    endwin();

    return 0;
}